blank_issues_enabled: false
contact_links:
  - name: clash.meta Community Support
    url: https://github.com/kitty314/1.17.0/discussions
    about: Please ask and answer questions about clash.meta here.
